import pymysql
import datetime
import hashlib


def save(insert_data, spider_type, now_date, spider_id):
    db = pymysql.connect(host="dcqljw.com", user="root", password="Dcq.159357", port=3306, db="dcqljw")
    cursor = db.cursor()
    # 插入spider_data
    sql = """INSERT INTO spider_data (spider_id,spider_type, note, crawl_time, source_data)
                VALUES (%s,%s,%s,%s,%s);"""
    cursor.executemany(sql, insert_data)

    # 插入spider_time
    insert_data = [
        (now_date, spider_type, spider_id)
    ]

    sql = """INSERT INTO spider_time (time, spider_type, spider_data_key)
                VALUES (%s,%s,%s);"""
    cursor.executemany(sql, insert_data)
    try:
        db.commit()
    except:
        db.rollback()
    cursor.close()
    db.close()


if __name__ == '__main__':
    data = [{'fun_word': 1, 'emoticon': '', 'extension': 16, 'word_scheme': '肖战真唱', 'flag_desc': '晚会',
             'topic_flag': 0, 'flag': 16, 'num': 907999, 'is_fei': 1, 'icon_desc': '沸', 'onboard_time': 1688051809,
             'category': '影视', 'icon_desc_color': '#f86400', 'small_icon_desc': '沸',
             'small_icon_desc_color': '#f86400', 'mid': '4918108714436544', 'raw_hot': 907999,
             'channel_type': 'Entertainment', 'subject_querys': '晚会|湾区升明月', 'ad_info': '',
             'subject_label': '晚会', 'star_name': ['肖战'], 'word': '肖战真唱', 'realpos': 1, 'expand': 0,
             'label_name': '沸', 'note': '肖战真唱', 'star_word': 0, 'rank': 0},
            {'fun_word': 1, 'emoticon': '', 'extension': 16, 'word_scheme': '#港星赢得很彻底#', 'flag_desc': '晚会',
             'topic_flag': 1, 'flag': 16, 'num': 640187, 'is_fei': 1, 'icon_desc': '沸', 'onboard_time': 1688046642,
             'category': '影视', 'icon_desc_color': '#f86400', 'small_icon_desc': '沸',
             'small_icon_desc_color': '#f86400', 'mid': '4918068361038939', 'raw_hot': 640187,
             'channel_type': 'Entertainment', 'subject_querys': '晚会|湾区升明月', 'ad_info': '',
             'subject_label': '晚会', 'star_name': {}, 'word': '港星赢得很彻底', 'realpos': 2, 'expand': 0,
             'label_name': '沸', 'note': '港星赢得很彻底', 'star_word': 0, 'rank': 1},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 605093,
             'onboard_time': 1688020476, 'category': '社会新闻', 'word_scheme': '#2023年中国网络文明大会新闻发布会#',
             'mid': '4917988581184292', 'raw_hot': 4063, 'subject_label': '', 'channel_type': '', 'subject_querys': '',
             'realpos': 3, 'star_name': {}, 'ad_info': '', 'word': '2023年中国网络文明大会新闻发布会', 'expand': 0,
             'label_name': '', 'note': '2023年中国网络文明大会新闻发布会', 'star_word': 0, 'rank': 2},
            {'fun_word': 1, 'emoticon': '', 'extension': 2, 'word_scheme': '刘浩存好漂亮', 'flag_desc': '晚会',
             'topic_flag': 0, 'flag': 2, 'num': 577883, 'icon_desc_color': '#ff9406', 'icon_desc': '热',
             'onboard_time': 1688049826, 'category': '影视', 'channel_type': 'Entertainment', 'small_icon_desc': '热',
             'small_icon_desc_color': '#ff9406', 'mid': '4918096492238146', 'raw_hot': 577883, 'is_hot': 1,
             'ad_info': '', 'word': '刘浩存好漂亮', 'subject_querys': '晚会|湾区升明月', 'star_name': ['刘浩存'],
             'realpos': 4, 'subject_label': '晚会', 'expand': 0, 'label_name': '热', 'note': '刘浩存好漂亮',
             'star_word': 0, 'rank': 3},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'flag_desc': '音乐', 'topic_flag': 0, 'flag': 0,
             'num': 469304, 'onboard_time': 1688053602, 'category': '音乐', 'word_scheme': '崔叡娜新歌下架',
             'mid': '4918093233527549', 'raw_hot': 469304, 'subject_label': '音乐', 'channel_type': 'Entertainment',
             'subject_querys': '', 'realpos': 5, 'star_name': ['崔叡娜'], 'ad_info': '', 'word': '崔叡娜新歌下架',
             'expand': 0, 'label_name': '', 'note': '崔叡娜新歌下架', 'star_word': 0, 'rank': 4},
            {'fun_word': 0, 'emoticon': '', 'extension': 2, 'word_scheme': 'LPL大瓜', 'topic_flag': 0, 'flag': 2,
             'num': 463204, 'icon_desc_color': '#ff9406', 'icon_desc': '热', 'onboard_time': 1688053602,
             'category': '游戏', 'channel_type': '', 'small_icon_desc': '热', 'small_icon_desc_color': '#ff9406',
             'mid': '4918099868913162', 'raw_hot': 1484073, 'is_hot': 1, 'ad_info': '', 'word': 'LPL大瓜',
             'subject_label': '', 'star_name': {}, 'realpos': 6, 'subject_querys': '', 'expand': 0, 'label_name': '热',
             'note': 'LPL大瓜', 'star_word': 0, 'rank': 5},
            {'start_time': 1688054400, 'nickname_show': 0, 'forbidden': {}, 'num': 461804, 'icon_desc': '商',
             'icon_type': 'jian', 'icon_desc_color': '#00b7ee', 'topic_ad': 1, 'is_ad': 1,
             'icon': 'https://simg.s.weibo.com/20180814113351_jian_28_0813.png', 'is_topic': 1, 'sort': 3, 'is_star': 1,
             'mobile_icon': {}, 'note': '平安京夏日庆典', 'ad_channel': 1, 'is_abtest': 0, 'topic_flag': 1, 'logo': '',
             'jump_scheme': '', 'small_icon_desc_color': '#00b7ee', 'mobile_icon_socialize': {},
             'small_icon_desc': '商', 'emoticon': '', 'poi': 6, 'id': 194629, 'monitor': {}, 'ad_type': '商业投放',
             'monitors': {'app': {}, 'pc': {}}, 'star_name': {}, 'updated_time': '1687858421', 'word': '平安京夏日庆典',
             'end_time': 1688140799, 'dot_icon': 1, 'pc_icon': {}, 'name': '#平安京夏日庆典#', 'rank': 5},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 0, 'flag': 0,
             'num': 452432, 'onboard_time': 1688053306, 'category': '影视', 'word_scheme': '章子怡压轴',
             'mid': '4918085486643739', 'raw_hot': 452432, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|湾区升明月', 'realpos': 7, 'star_name': ['章子怡'], 'ad_info': '',
             'word': '章子怡压轴', 'expand': 0, 'label_name': '', 'note': '章子怡压轴', 'star_word': 0, 'rank': 6},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 0, 'flag': 0, 'num': 302950,
             'onboard_time': 1688041832, 'category': '旅游', 'word_scheme': '去故宫的时候一定要抬头',
             'mid': '4917922445922448', 'raw_hot': 302950, 'subject_label': '', 'channel_type': '',
             'subject_querys': '', 'realpos': 8, 'star_name': {}, 'ad_info': '', 'word': '去故宫的时候一定要抬头',
             'expand': 0, 'label_name': '', 'note': '去故宫的时候一定要抬头', 'star_word': 0, 'rank': 7},
            {'fun_word': 0, 'emoticon': '', 'extension': 32768, 'is_warm': 1, 'topic_flag': 1, 'flag': 32768,
             'num': 251455, 'icon_desc_color': '#ffab5a', 'icon_desc': '暖', 'onboard_time': 1688044239,
             'category': '社会新闻,教育', 'channel_type': '', 'small_icon_desc': '暖',
             'small_icon_desc_color': '#ffab5a', 'mid': '4917918628054946', 'raw_hot': 251455, 'subject_querys': '',
             'ad_info': '', 'word': '学霸情侣本科毕业齐直博被校长写进致辞', 'subject_label': '', 'star_name': {},
             'realpos': 9, 'word_scheme': '#学霸情侣本科毕业齐直博被校长写进致辞#', 'expand': 0, 'label_name': '暖',
             'note': '学霸情侣本科毕业齐直博被校长写进致辞', 'star_word': 0, 'rank': 8},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 251381,
             'onboard_time': 1688042499, 'category': '财经', 'word_scheme': '#为什么火锅价格越来越贵了#',
             'mid': '4918022524899436', 'raw_hot': 227221, 'subject_label': '', 'channel_type': '',
             'subject_querys': '', 'realpos': 10, 'star_name': {}, 'ad_info': '', 'word': '为什么火锅价格越来越贵了',
             'expand': 0, 'label_name': '', 'note': '为什么火锅价格越来越贵了', 'star_word': 0, 'rank': 9},
            {'fun_word': 1, 'emoticon': '', 'extension': 1, 'word_scheme': '#殷世航当花童#', 'topic_flag': 1, 'flag': 1,
             'num': 251106, 'icon_desc_color': '#ff3852', 'icon_desc': '新', 'onboard_time': 1688055993,
             'category': '网红', 'channel_type': 'Entertainment', 'small_icon_desc': '新',
             'small_icon_desc_color': '#ff3852', 'mid': '4918107221789261', 'raw_hot': 791273, 'subject_querys': '',
             'ad_info': '', 'is_new': 1, 'subject_label': '', 'star_name': {}, 'word': '殷世航当花童', 'realpos': 11,
             'expand': 0, 'label_name': '新', 'note': '殷世航当花童', 'star_word': 0, 'rank': 10},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'topic_flag': 0, 'flag': 0, 'num': 250514,
             'onboard_time': 1688026115, 'category': '艺人', 'word_scheme': '范玮琪 我丈夫是个正直的人',
             'mid': '4917995795120505', 'raw_hot': 444452, 'subject_label': '', 'channel_type': 'Entertainment',
             'subject_querys': '', 'realpos': 12, 'star_name': {}, 'ad_info': '', 'word': '范玮琪 我丈夫是个正直的人',
             'expand': 0, 'label_name': '', 'note': '范玮琪 我丈夫是个正直的人', 'star_word': 1, 'rank': 11},
            {'fun_word': 1, 'emoticon': '', 'extension': 1, 'word_scheme': '周杰伦演唱会', 'flag_desc': '音乐',
             'topic_flag': 0, 'flag': 1, 'num': 250281, 'icon_desc_color': '#ff3852', 'icon_desc': '新',
             'onboard_time': 1688054976, 'category': '音乐', 'channel_type': 'Entertainment', 'small_icon_desc': '新',
             'small_icon_desc_color': '#ff3852', 'mid': '4918127189558011', 'raw_hot': 396711, 'subject_label': '音乐',
             'ad_info': '', 'is_new': 1, 'subject_querys': '', 'star_name': ['周杰伦'], 'word': '周杰伦演唱会',
             'realpos': 13, 'expand': 0, 'label_name': '新', 'note': '周杰伦演唱会', 'star_word': 0, 'rank': 12},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 249845,
             'onboard_time': 1688024857, 'category': '科技', 'word_scheme': '#微信官方致歉#', 'mid': '4918003429016238',
             'raw_hot': 360193, 'subject_label': '', 'channel_type': '', 'subject_querys': '', 'realpos': 14,
             'star_name': {}, 'ad_info': '', 'word': '微信官方致歉', 'expand': 0, 'label_name': '',
             'note': '微信官方致歉', 'star_word': 0, 'rank': 13},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 0, 'flag': 0, 'num': 249789,
             'onboard_time': 1688052771, 'category': '体育', 'word_scheme': 'wtt', 'mid': '4918004033521210',
             'raw_hot': 164961, 'subject_label': '', 'channel_type': '', 'subject_querys': '', 'realpos': 15,
             'star_name': {}, 'ad_info': '', 'word': 'wtt', 'expand': 0, 'label_name': '', 'note': 'wtt',
             'star_word': 0, 'rank': 14},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 249218,
             'onboard_time': 1688030738, 'category': '艺人', 'word_scheme': '#黑涩会美眉妖娇指控陈建州性骚扰#',
             'mid': '4918020592373972', 'raw_hot': 345118, 'subject_label': '', 'channel_type': 'Entertainment',
             'subject_querys': '', 'realpos': 16, 'star_name': {}, 'ad_info': '',
             'word': '黑涩会美眉妖娇指控陈建州性骚扰', 'expand': 0, 'label_name': '',
             'note': '黑涩会美眉妖娇指控陈建州性骚扰', 'star_word': 1, 'rank': 15},
            {'fun_word': 1, 'emoticon': '[舔屏]', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 0, 'flag': 0,
             'num': 249106, 'onboard_time': 1688047425, 'category': '影视', 'word_scheme': '关晓彤这腿',
             'mid': '4918087491262807', 'raw_hot': 331146, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|湾区升明月', 'realpos': 17, 'star_name': ['关晓彤'], 'ad_info': '',
             'word': '关晓彤这腿', 'expand': 0, 'label_name': '', 'note': '关晓彤这腿', 'star_word': 0, 'rank': 16},
            {'fun_word': 0, 'emoticon': '', 'extension': 1, 'word_scheme': '#樊振东3比0安宰贤#', 'topic_flag': 1,
             'flag': 1, 'num': 248807, 'icon_desc_color': '#ff3852', 'icon_desc': '新', 'onboard_time': 1688054437,
             'category': '体育', 'channel_type': '', 'small_icon_desc': '新', 'small_icon_desc_color': '#ff3852',
             'mid': '4918079975326434', 'raw_hot': 160357, 'subject_querys': '', 'ad_info': '', 'is_new': 1,
             'subject_label': '', 'star_name': ['安宰贤'], 'word': '樊振东3比0安宰贤', 'realpos': 18, 'expand': 0,
             'label_name': '新', 'note': '樊振东3比0安宰贤', 'star_word': 0, 'rank': 17},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 248336,
             'onboard_time': 1688047365, 'category': '社会新闻', 'word_scheme': '#重庆客车被落石砸中致6死9伤#',
             'mid': '4918096324990888', 'raw_hot': 138293, 'subject_label': '', 'channel_type': '',
             'subject_querys': '', 'realpos': 19, 'star_name': {}, 'ad_info': '', 'word': '重庆客车被落石砸中致6死9伤',
             'expand': 0, 'label_name': '', 'note': '重庆客车被落石砸中致6死9伤', 'star_word': 0, 'rank': 18},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 247976,
             'onboard_time': 1688050545, 'category': '社会新闻', 'word_scheme': '#官方回应山西代县瞒报17名矿工死亡#',
             'mid': '4918113910660590', 'raw_hot': 136973, 'subject_label': '', 'channel_type': '',
             'subject_querys': '', 'realpos': 20, 'star_name': {}, 'ad_info': '',
             'word': '官方回应山西代县瞒报17名矿工死亡', 'expand': 0, 'label_name': '',
             'note': '官方回应山西代县瞒报17名矿工死亡', 'star_word': 0, 'rank': 19},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 0, 'flag': 0,
             'num': 247561, 'onboard_time': 1688048507, 'category': '影视', 'word_scheme': '周深修音响第一人',
             'mid': '4918098589388529', 'raw_hot': 319425, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|湾区升明月', 'realpos': 21, 'star_name': ['周深'], 'ad_info': '',
             'word': '周深修音响第一人', 'expand': 0, 'label_name': '', 'note': '周深修音响第一人', 'star_word': 0,
             'rank': 20},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 1, 'flag': 0,
             'num': 247290, 'onboard_time': 1688053248, 'category': '影视', 'word_scheme': '#吴京把苏有朋唱卡壳了#',
             'mid': '4918083074662085', 'raw_hot': 311617, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|2023湾区升明月大湾区电影音乐晚会', 'realpos': 22, 'star_name': ['吴京'],
             'ad_info': '', 'word': '吴京把苏有朋唱卡壳了', 'expand': 0, 'label_name': '',
             'note': '吴京把苏有朋唱卡壳了', 'star_word': 0, 'rank': 21},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 247135,
             'onboard_time': 1688050368, 'category': '财经,幽默', 'word_scheme': '#月薪5000真的有点低#',
             'mid': '4918106512955306', 'raw_hot': 290422, 'subject_label': '', 'channel_type': '',
             'subject_querys': '', 'realpos': 23, 'star_name': {}, 'ad_info': '', 'word': '月薪5000真的有点低',
             'expand': 0, 'label_name': '', 'note': '月薪5000真的有点低', 'star_word': 0, 'rank': 22},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 246589,
             'onboard_time': 1688050969, 'category': '社会新闻', 'word_scheme': '#蜱虫在老人脖子上吸完血大如黄豆#',
             'mid': '4918043476495341', 'raw_hot': 161815, 'subject_label': '', 'channel_type': '',
             'subject_querys': '', 'realpos': 24, 'star_name': {}, 'ad_info': '',
             'word': '蜱虫在老人脖子上吸完血大如黄豆', 'expand': 0, 'label_name': '',
             'note': '蜱虫在老人脖子上吸完血大如黄豆', 'star_word': 0, 'rank': 23},
            {'fun_word': 0, 'emoticon': '', 'extension': 1, 'word_scheme': '眼睛功能问题康复小方法', 'topic_flag': 0,
             'flag': 1, 'num': 246453, 'icon_desc_color': '#ff3852', 'icon_desc': '新', 'onboard_time': 1688055215,
             'category': '社会新闻,科技', 'channel_type': '', 'small_icon_desc': '新',
             'small_icon_desc_color': '#ff3852', 'mid': '4917921435091139', 'raw_hot': 157295, 'subject_querys': '',
             'ad_info': '', 'is_new': 1, 'subject_label': '', 'star_name': {}, 'word': '眼睛功能问题康复小方法',
             'realpos': 25, 'expand': 0, 'label_name': '新', 'note': '眼睛功能问题康复小方法', 'star_word': 0,
             'rank': 24},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 0, 'flag': 0,
             'num': 246167, 'onboard_time': 1688047425, 'category': '影视', 'word_scheme': '许嵩挽回了面子',
             'mid': '4918084748185995', 'raw_hot': 246167, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|湾区升明月', 'realpos': 26, 'star_name': ['许嵩'], 'ad_info': '',
             'word': '许嵩挽回了面子', 'expand': 0, 'label_name': '', 'note': '许嵩挽回了面子', 'star_word': 0,
             'rank': 25}, {'fun_word': 1, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 240240,
                           'onboard_time': 1688027077, 'category': '艺人', 'word_scheme': '#Ella自曝出道后被性骚扰#',
                           'mid': '4917996864673280', 'raw_hot': 240240, 'subject_label': '',
                           'channel_type': 'Entertainment', 'subject_querys': '', 'realpos': 27, 'star_name': ['ella'],
                           'ad_info': '', 'word': 'Ella自曝出道后被性骚扰', 'expand': 0, 'label_name': '',
                           'note': 'Ella自曝出道后被性骚扰', 'star_word': 1, 'rank': 26},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 231513,
             'onboard_time': 1688028460, 'category': '艺人', 'word_scheme': '#关晓彤帽子P掉了鹿晗品牌#',
             'mid': '4918010148557107', 'raw_hot': 231513, 'subject_label': '', 'channel_type': 'Entertainment',
             'subject_querys': '', 'realpos': 28, 'star_name': ['关晓彤'], 'ad_info': '',
             'word': '关晓彤帽子P掉了鹿晗品牌', 'expand': 0, 'label_name': '', 'note': '关晓彤帽子P掉了鹿晗品牌',
             'star_word': 1, 'rank': 27},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'flag_desc': '投票', 'topic_flag': 1, 'flag': 0,
             'num': 225684, 'onboard_time': 1688032059, 'category': '科技',
             'word_scheme': '#微信支付的手续费是否过高了#', 'mid': '4918026077476996', 'raw_hot': 128672,
             'subject_label': '投票', 'channel_type': '', 'subject_querys': '', 'realpos': 29, 'star_name': {},
             'ad_info': '', 'word': '微信支付的手续费是否过高了', 'expand': 0, 'label_name': '',
             'note': '微信支付的手续费是否过高了', 'star_word': 0, 'rank': 28},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 224629,
             'onboard_time': 1688037573, 'category': '幽默,社会新闻', 'word_scheme': '#背帆布包上班被同事阴阳了#',
             'mid': '4918088694241391', 'raw_hot': 124748, 'subject_label': '', 'channel_type': '',
             'subject_querys': '', 'realpos': 30, 'star_name': {}, 'ad_info': '', 'word': '背帆布包上班被同事阴阳了',
             'expand': 0, 'label_name': '', 'note': '背帆布包上班被同事阴阳了', 'star_word': 0, 'rank': 29},
            {'fun_word': 1, 'emoticon': '[泪]', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 0, 'flag': 0,
             'num': 223700, 'onboard_time': 1688042859, 'category': '影视', 'word_scheme': '张柏芝美得我眼前一亮',
             'mid': '4918069803617905', 'raw_hot': 223700, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|湾区升明月', 'realpos': 31, 'star_name': ['张柏芝'], 'ad_info': '',
             'word': '张柏芝美得我眼前一亮', 'expand': 0, 'label_name': '', 'note': '张柏芝美得我眼前一亮',
             'star_word': 0, 'rank': 30},
            {'fun_word': 1, 'emoticon': '', 'extension': 1, 'word_scheme': '鉴证实录', 'flag_desc': '晚会',
             'topic_flag': 0, 'flag': 1, 'num': 223597, 'icon_desc_color': '#ff3852', 'icon_desc': '新',
             'onboard_time': 1688058325, 'category': '影视', 'channel_type': 'Entertainment', 'small_icon_desc': '新',
             'small_icon_desc_color': '#ff3852', 'mid': '4918096106365238', 'raw_hot': 223597, 'subject_label': '晚会',
             'ad_info': '', 'is_new': 1, 'subject_querys': '剧集|鉴证实录,晚会|湾区升明月', 'star_name': {},
             'word': '鉴证实录', 'realpos': 32, 'expand': 0, 'label_name': '新', 'note': '鉴证实录', 'star_word': 0,
             'rank': 31}, {'fun_word': 1, 'emoticon': '', 'extension': 1, 'word_scheme': '#郁可唯大湾区再唱水中花#',
                           'flag_desc': '晚会', 'topic_flag': 1, 'flag': 1, 'num': 213368, 'icon_desc_color': '#ff3852',
                           'icon_desc': '新', 'onboard_time': 1688055274, 'category': '影视',
                           'channel_type': 'Entertainment', 'small_icon_desc': '新', 'small_icon_desc_color': '#ff3852',
                           'mid': '4918085707894041', 'raw_hot': 213368, 'subject_label': '晚会', 'ad_info': '',
                           'is_new': 1, 'subject_querys': '晚会|2023湾区升明月大湾区电影音乐晚会',
                           'star_name': ['郁可唯'], 'word': '郁可唯大湾区再唱水中花', 'realpos': 33, 'expand': 0,
                           'label_name': '新', 'note': '郁可唯大湾区再唱水中花', 'star_word': 0, 'rank': 32},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 0, 'flag': 0,
             'num': 210285, 'onboard_time': 1688041357, 'category': '影视', 'word_scheme': '华晨宇发挥',
             'mid': '4918085058828865', 'raw_hot': 210285, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|湾区升明月', 'realpos': 34, 'star_name': ['华晨宇'], 'ad_info': '',
             'word': '华晨宇发挥', 'expand': 0, 'label_name': '', 'note': '华晨宇发挥', 'star_word': 0, 'rank': 33},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 192767,
             'onboard_time': 1688028520, 'category': '财经', 'word_scheme': '#LV帆布袋已被炒至700元#',
             'mid': '4918013783966085', 'raw_hot': 110734, 'subject_label': '', 'channel_type': '',
             'subject_querys': '', 'realpos': 35, 'star_name': {}, 'ad_info': '', 'word': 'LV帆布袋已被炒至700元',
             'expand': 0, 'label_name': '', 'note': 'LV帆布袋已被炒至700元', 'star_word': 0, 'rank': 34},
            {'fun_word': 1, 'emoticon': '', 'extension': 1, 'word_scheme': '十个勤天', 'flag_desc': '综艺',
             'topic_flag': 0, 'flag': 1, 'num': 184186, 'icon_desc_color': '#ff3852', 'icon_desc': '新',
             'onboard_time': 1688058924, 'category': '综艺', 'channel_type': 'Entertainment', 'small_icon_desc': '新',
             'small_icon_desc_color': '#ff3852', 'mid': '4918127895512348', 'raw_hot': 184186, 'subject_label': '综艺',
             'ad_info': '', 'is_new': 1, 'subject_querys': '综艺|种地吧', 'star_name': {}, 'word': '十个勤天',
             'realpos': 36, 'expand': 0, 'label_name': '新', 'note': '十个勤天', 'star_word': 0, 'rank': 35},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 182692,
             'onboard_time': 1688042559, 'category': '幽默', 'word_scheme': '#如果不工作5万可以用多久#',
             'mid': '4918084332161615', 'raw_hot': 105493, 'subject_label': '', 'channel_type': '',
             'subject_querys': '', 'realpos': 37, 'star_name': {}, 'ad_info': '', 'word': '如果不工作5万可以用多久',
             'expand': 0, 'label_name': '', 'note': '如果不工作5万可以用多久', 'star_word': 0, 'rank': 36},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 181366,
             'onboard_time': 1688035778, 'category': '社会新闻,教育', 'word_scheme': '#19岁男生高考后找失足女被拘5天#',
             'mid': '4917977113953668', 'raw_hot': 97593, 'subject_label': '', 'channel_type': '', 'subject_querys': '',
             'realpos': 38, 'star_name': {}, 'ad_info': '', 'word': '19岁男生高考后找失足女被拘5天', 'expand': 0,
             'label_name': '', 'note': '19岁男生高考后找失足女被拘5天', 'star_word': 0, 'rank': 37},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 179120,
             'onboard_time': 1688041956, 'category': '国内要闻', 'word_scheme': '#武契奇儿子被科索沃当局扣留#',
             'mid': '4918004028277158', 'raw_hot': 96348, 'subject_label': '', 'channel_type': '', 'subject_querys': '',
             'realpos': 39, 'star_name': {}, 'ad_info': '', 'word': '武契奇儿子被科索沃当局扣留', 'expand': 0,
             'label_name': '', 'note': '武契奇儿子被科索沃当局扣留', 'star_word': 0, 'rank': 38},
            {'fun_word': 0, 'emoticon': '', 'extension': 1, 'word_scheme': '将杀', 'topic_flag': 0, 'flag': 1,
             'num': 177230, 'icon_desc_color': '#ff3852', 'icon_desc': '新', 'onboard_time': 1688056171,
             'category': '游戏', 'channel_type': '', 'small_icon_desc': '新', 'small_icon_desc_color': '#ff3852',
             'mid': '4918075579433893', 'raw_hot': 93360, 'subject_querys': '', 'ad_info': '', 'is_new': 1,
             'subject_label': '', 'star_name': {}, 'word': '将杀', 'realpos': 40, 'expand': 0, 'label_name': '新',
             'note': '将杀', 'star_word': 0, 'rank': 39},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 176504,
             'onboard_time': 1688036434, 'category': '艺人', 'word_scheme': '#辛芷蕾自曝小时候遭遇猥亵#',
             'mid': '4918051025719995', 'raw_hot': 176504, 'subject_label': '', 'channel_type': 'Entertainment',
             'subject_querys': '', 'realpos': 41, 'star_name': ['辛芷蕾'], 'ad_info': '',
             'word': '辛芷蕾自曝小时候遭遇猥亵', 'expand': 0, 'label_name': '', 'note': '辛芷蕾自曝小时候遭遇猥亵',
             'star_word': 1, 'rank': 40},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 1, 'flag': 0,
             'num': 162841, 'onboard_time': 1688052527, 'category': '影视', 'word_scheme': '#肖战潇洒走一回#',
             'mid': '4918109531539035', 'raw_hot': 162841, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|湾区升明月', 'realpos': 42, 'star_name': ['肖战'], 'ad_info': '',
             'word': '肖战潇洒走一回', 'expand': 0, 'label_name': '', 'note': '肖战潇洒走一回', 'star_word': 0,
             'rank': 41}, {'fun_word': 1, 'emoticon': '', 'extension': 0, 'topic_flag': 1, 'flag': 0, 'num': 135246,
                           'onboard_time': 1688053424, 'category': '影视',
                           'word_scheme': '#李玉刚刘浩存魏大勋胡先煦范世錡合唱万疆#', 'mid': '4918103525825284',
                           'raw_hot': 135246, 'subject_label': '', 'channel_type': 'Entertainment',
                           'subject_querys': '', 'realpos': 43,
                           'star_name': ['胡先煦', '李玉刚', '万疆', '魏大勋', '刘浩存', '范世锜'], 'ad_info': '',
                           'word': '李玉刚刘浩存魏大勋胡先煦范世錡合唱万疆', 'expand': 0, 'label_name': '',
                           'note': '李玉刚刘浩存魏大勋胡先煦范世錡合唱万疆', 'star_word': 0, 'rank': 42},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 0, 'flag': 0,
             'num': 134728, 'onboard_time': 1688051566, 'category': '影视', 'word_scheme': '张靓颖上大分',
             'mid': '4918109909029516', 'raw_hot': 134728, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|湾区升明月', 'realpos': 44, 'star_name': ['张靓颖'], 'ad_info': '',
             'word': '张靓颖上大分', 'expand': 0, 'label_name': '', 'note': '张靓颖上大分', 'star_word': 0, 'rank': 43},
            {'fun_word': 1, 'emoticon': '', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 0, 'flag': 0,
             'num': 134513, 'onboard_time': 1688052407, 'category': '影视', 'word_scheme': '周笔畅全开麦',
             'mid': '4918126410467481', 'raw_hot': 134513, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|湾区升明月', 'realpos': 45, 'star_name': ['周笔畅'], 'ad_info': '',
             'word': '周笔畅全开麦', 'expand': 0, 'label_name': '', 'note': '周笔畅全开麦', 'star_word': 0, 'rank': 44},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'topic_flag': 0, 'flag': 0, 'num': 130671,
             'onboard_time': 1688047603, 'category': '幽默', 'word_scheme': '戴这俩冰袖是为了啥',
             'mid': '4917924022455170', 'raw_hot': 87141, 'subject_label': '', 'channel_type': '', 'subject_querys': '',
             'realpos': 46, 'star_name': {}, 'ad_info': '', 'word': '戴这俩冰袖是为了啥', 'expand': 0, 'label_name': '',
             'note': '戴这俩冰袖是为了啥', 'star_word': 0, 'rank': 45},
            {'fun_word': 1, 'emoticon': '[泪]', 'extension': 0, 'flag_desc': '晚会', 'topic_flag': 0, 'flag': 0,
             'num': 128791, 'onboard_time': 1688049405, 'category': '影视', 'word_scheme': '林保怡 陈慧珊',
             'mid': '4918096106365238', 'raw_hot': 128791, 'subject_label': '晚会', 'channel_type': 'Entertainment',
             'subject_querys': '晚会|湾区升明月,剧集|鉴证实录', 'realpos': 47, 'star_name': ['陈慧珊', '林保怡'],
             'ad_info': '', 'word': '林保怡 陈慧珊', 'expand': 0, 'label_name': '', 'note': '林保怡 陈慧珊',
             'star_word': 0, 'rank': 46},
            {'fun_word': 0, 'emoticon': '', 'extension': 0, 'flag_desc': '投票', 'topic_flag': 1, 'flag': 0,
             'num': 128327, 'onboard_time': 1688026837, 'category': '科技,社会新闻',
             'word_scheme': '#支付软件开始收费你还会用吗#', 'mid': '4918007212279038', 'raw_hot': 88623,
             'subject_label': '投票', 'channel_type': '', 'subject_querys': '', 'realpos': 48, 'star_name': {},
             'ad_info': '', 'word': '支付软件开始收费你还会用吗', 'expand': 0, 'label_name': '',
             'note': '支付软件开始收费你还会用吗', 'star_word': 0, 'rank': 47},
            {'fun_word': 0, 'emoticon': '', 'extension': 1, 'word_scheme': '预防人贩子骗你开门', 'topic_flag': 0,
             'flag': 1, 'num': 127746, 'icon_desc_color': '#ff3852', 'icon_desc': '新', 'onboard_time': 1688057727,
             'category': '社会新闻', 'channel_type': '', 'small_icon_desc': '新', 'small_icon_desc_color': '#ff3852',
             'mid': '4917745358213989', 'raw_hot': 87721, 'subject_querys': '', 'ad_info': '', 'is_new': 1,
             'subject_label': '', 'star_name': {}, 'word': '预防人贩子骗你开门', 'realpos': 49, 'expand': 0,
             'label_name': '新', 'note': '预防人贩子骗你开门', 'star_word': 0, 'rank': 48},
            {'fun_word': 0, 'emoticon': '', 'extension': 32768, 'is_warm': 1, 'topic_flag': 1, 'flag': 32768,
             'num': 126999, 'icon_desc_color': '#ffab5a', 'icon_desc': '暖', 'onboard_time': 1688050907,
             'category': '社会新闻', 'channel_type': '', 'small_icon_desc': '暖', 'small_icon_desc_color': '#ffab5a',
             'mid': '4918119203866676', 'raw_hot': 73903, 'subject_querys': '', 'ad_info': '',
             'word': '大熊猫雅一把秋千坐断了', 'subject_label': '', 'star_name': {}, 'realpos': 50,
             'word_scheme': '#大熊猫雅一把秋千坐断了#', 'expand': 0, 'label_name': '暖',
             'note': '大熊猫雅一把秋千坐断了', 'star_word': 0, 'rank': 49}]
    save(data, "weibo")
